[workspace]
members = [".", "metadata"]

[package]
name = "cargo-contract"
version = "0.7.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://substrate.dev/substrate-contracts-workshop/#/"
homepage = "https://www.parity.io/"
description = "Setup and deployment tool for developing Wasm based smart contracts via ink!"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["command-line-utilities", "development-tools::build-utils", "development-tools::cargo-plugins"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE", "build.rs", "template"]

[dependencies]
env_logger = "0.7.1"
anyhow = "1.0.32"
structopt = "0.3.16"
log = "0.4.11"
heck = "0.3.1"
zip = { version = "0.5.6", default-features = false }
pwasm-utils = "0.14.0"
parity-wasm = "0.41.0"
cargo_metadata = "0.11.1"
scale = { package = "parity-scale-codec", version = "1.3.4" }
which = "4.0.2"
colored = "2.0.0"
toml = "0.5.6"
cargo-xbuild = "0.6.0"
rustc_version = "0.2.3"
blake2 = "0.9.0"
contract-metadata = { version = "0.1.0", path = "./metadata" }
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.115", default-features = false, features = ["derive"] }
serde_json = "1.0.57"
tempfile = "3.1.0"
url = { version = "2.1.1", features = ["serde"] }

# dependencies for optional extrinsics feature
async-std = { version = "1.6.2", optional = true }
ink_metadata = { version = "3.0.0-rc1", optional = true }
scale-info = { version = "0.4", default-features = false, features = ["derive"], optional = true }
sp-core = { version = "2.0.0", optional = true }
subxt = { version = "0.13.0", package = "substrate-subxt", optional = true }
futures = { version = "0.3.5", optional = true }
hex = { version = "0.4.2", optional = true }
jsonrpsee = "0.1.0"
sp-rpc = "2.0.0"
ron = { version = "0.6.2", features = ["indexmap"] }
nom = "5.1.2"
indexmap = "1.6.0"
thiserror = "1.0.21"

[build-dependencies]
anyhow = "1.0.32"
zip = { version = "0.5.6", default-features = false }
walkdir = "2.3.1"

[dev-dependencies]
assert_matches = "1.3.0"
pretty_assertions = "0.6.1"
wabt = "0.10.0"
ink_primitives = "3.0.0-rc1"
ink_env = "3.0.0-rc1"
ink_storage = "3.0.0-rc1"
ink_lang = "3.0.0-rc1"

[features]
default = ["std"]
std = []

# Enable this for (experimental) commands to deploy, instantiate and call contracts.
#
# Disabled by default
extrinsics = ["ink_metadata", "scale-info", "sp-core", "subxt", "async-std", "futures", "hex"]

# Enable this to execute long running tests, which usually are only run on the CI server
#
# Disabled by default
test-ci-only = []
